import { Cairo } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import Location from "./_components/OurLocation";

<script src="../path/to/flowbite/dist/flowbite.min.js"></script>
const inter = Cairo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {dir} from "i18next"
import languages from "../i18n/settings";
export async function generationStatic(){
    return languages.map((lng)=>{lng})
}
console.log(1);
export default function RootLayout({ 
    children,
    params:{ lng} 
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Header lng={lng}/>
        {children}
        <Location lng={lng}/>

        <Footer lng={lng}/>
            
      </body>
    </html>
  );
}
/* HTML: <div class="loader"></div> */
